name: Build and Release

on:
  push:
    branches: [ Avalonia_dotnet_8 ]
    tags:
      - 'v*'  # Push to tags starting with v

  pull_request:
    branches: [ Avalonia_dotnet_8 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish PingDVD/PingDVD.csproj -c Release -r ${{ matrix.os }} --self-contained false /p:PublishTrimmed=false /p:PublishSingleFile=false --output ./publish/${{ matrix.os }}

    - name: Create ZIP archive
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          cd publish/windows-latest && Compress-Archive -Path * -DestinationPath ../../PingDVD-Windows.zip
        else
          cd publish/macos-latest && zip -r ../../PingDVD-macOS.zip .
        fi

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: PingDVD-${{ runner.os }}
        path: PingDVD-*.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: PingDVD-*.zip
        generate_release_notes: true